CREATE(Lego:Produit{titre:'Lego CR7',prix:777,decs:'Lego de CR7',dispo:true,exp:true})
CREATE(Pc:Produit{titre:'Pc',prix:111,decs:'un petit pc',dispo:true,exp:true})
CREATE(BootsCR7:Produit{titre:'BootsCR7',prix:9999,decs:'The GOAT s BOOTS',dispo:false,exp:false})
CREATE(Pool:Produit{titre:'Pool',prix:65,decs:'A red pool',dispo:true,exp:true})
CREATE(Chair:Produit{titre:'Chaire',prix:10,decs:'A chaire',dispo:true,exp:false})
CREATE(Table:Produit{titre:'Table',prix:22,decs:'Une table',dispo:false,exp:false})
CREATE(CR7TOWER:Produit{titre:'CR7 TOWER',prix:1999999990,decs:'TOWER OF THE GOAT',dispo:false,exp:false})
CREATE(CR7CAR:Produit{titre:'CR7 s CAR',prix:222222,decs:'CAR of the GOAT',dispo:false,exp:false})
CREATE(CR7SHIRT:Produit{titre:'CR7 Shirt',prix:1000,decs:'Shirt of THE GOAT',dispo:true,exp:false})
CREATE(R9Boots:Produit{titre:'R9 s Boots',prix:100,decs:'Boots of r9',dispo:false,exp:false})

CREATE(NOA:Client{nom:'NOA', email:'noa@gmail.com'})
CREATE(MOHA:Client{nom:'MOHA', email:'moha@gmail.com'})
CREATE(MOHAMMED:client{nom:'MOHAMMED', email:'momo@gmail.com'})
CREATE(THEO:Client{nom:'THEO', email:'theo@gmail.com'})
CREATE(TITOUAN:Client{nom:'TITOUAN', email:'titouan@gmail.com'})

CREATE(IMMOBILIER:Categorie{titre:'Immobilier'})
CREATE(VETEMENT:Categorie{titre:'Vetement'})
CREATE(INFORMATIQUE:Categorie{titre:'Informatique'})

CREATE(Lego)-[liason1:APPARTIENT]->(IMMOBILIER)
CREATE(Pc)-[liason2:APPARTIENT]->(INFORMATIQUE)
CREATE(BootsCR7)-[liason3:APPARTIENT]->(VETEMENT)
CREATE(Pool)-[liason4:APPARTIENT]->(IMMOBILIER)
CREATE(Chair)-[liason5:APPARTIENT]->(IMMOBILIER)
CREATE(Table)-[liason6:APPARTIENT]->(IMMOBILIER)
CREATE(CR7TOWER)-[liason7:APPARTIENT]->(IMMOBILIER)
CREATE(CR7CAR)-[liason8:APPARTIENT]->(IMMOBILIER)
CREATE(CR7SHIRT)-[liason9:APPARTIENT]->(VETEMENT)
CREATE(R9Boots)-[liason10:APPARTIENT]->(VETEMENT)

CREATE(NOA)-[liason11:VOIR]->(Lego)
CREATE(MOHA)-[liason12:VOIR]->(Pc)
CREATE(MOHAMMED)-[liason13:VOLE]->(BootsCR7)
CREATE(THEO)-[liason14:ACHETE]->(Pool)
CREATE(TITOUAN)-[liason15:ACHETE]->(Chair)
CREATE(NOA)-[liason16:ACHETE]->(Table)
CREATE(TITOUAN)-[liason17:VOIR]->(CR7TOWER)
CREATE(NOA)-[liason18:VOIR]->(CR7CAR)
CREATE(MOHAMMED)-[liason19:ACHETE]->(CR7SHIRT)
CREATE(NOA)-[liason20:WISHLIST]->(R9Boots)
CREATE(MOHAMMED)-[liason21:VOLE]->(CR7CAR)

